In [ ]:
import numpy as np
print("Numpy version ", np.__version__)

NumPy version: 2.5.1


In [9]:
ar1 = np.array([1,2,3,4,5])
print("array 1:", ar1)

arr2 = np.array([[6,7,8],[3,9,10]])
print("array 2:\n", arr2)

arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("array 3:\n", arr3)

array 1: [1 2 3 4 5]
array 2:
 [[ 6  7  8]
 [ 3  9 10]]
array 3:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
zero_arr = np.zeros((2,3))
print("Zero array:\n", zero_arr)

one_arr = np.ones((3,2))
print("One array:\n", one_arr)

full_arr = np.full((2,2), 7)
print("Full array:\n", full_arr)

identity_arr = np.eye(3)
print("Identity array:\n", identity_arr)

identity_arr_2 = np.identity(4)
print("Identity array 2:\n", identity_arr_2)

Zero array:
 [[0. 0. 0.]
 [0. 0. 0.]]
One array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Full array:
 [[7 7]
 [7 7]]
Identity array:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Identity array 2:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
